Disabled downloading of VLogs
Dad-Ju/hbz-discord-bot pull request #2
Opened 2020-09-06 12:03 UTC by Gandalf1783

2020-09-09 14:23 UTC, Dad-Ju requested changes
Change it plz

2020-09-09 14:23 UTC, Dad-Ju commented on events/music-start.js
> +        } else if (newVoice == null) {
what for ?

2020-09-09 14:23 UTC, Dad-Ju commented on modules/yt.js
> +      videoInfo.title.includes("VLog") ||  // Check if this video
eventuell to lowercase konvertieren und dann checken ob keywords drin sind. dadurch sind wir unabhängig von Groß-Klein schreibung

2020-09-09 14:23 UTC, Dad-Ju commented on modules/yt.js
>          .pipe(fs.createWriteStream(`videos/${videoInfo.id}.mp3`))
von video id zu titel wechsel ?

2020-09-09 14:58 UTC, Gandalf1783 commented on events/music-start.js
> +        } else if (newVoice == null) {
Case if a user leaves

2020-09-09 14:59 UTC, Gandalf1783 commented on modules/yt.js
> +      videoInfo.title.includes("VLog") ||  // Check if this video
Alright, wird bearbeitet

2020-09-09 15:00 UTC, Gandalf1783 commented on modules/yt.js
>          .pipe(fs.createWriteStream(`videos/${videoInfo.id}.mp3`))
Ne is ja dazu gedacht dass die Vlogs gefiltert werden...

2020-09-17 10:43 UTC, Dad-Ju commented on events/music-start.js
> +        } else if (newVoice == null) {
wenn es keine Funktion hat raus. die klammer ist leer

2020-09-17 10:44 UTC, Dad-Ju commented on modules/yt.js
> +      videoInfo.title.includes("VLog") ||  // Check if this video
Update?

2020-09-17 10:45 UTC, Dad-Ju commented on modules/yt.js
>          .pipe(fs.createWriteStream(`videos/${videoInfo.id}.mp3`))
ìch meine damit das wir die videos auch mit dem namen abspeichern. nicht nur mit der id. vorteil wir können die json weg lassen  zum anzeigen in der presence.

2020-09-20 12:13 UTC, Gandalf1783 commented on modules/yt.js
> +      videoInfo.title.includes("VLog") ||  // Check if this video
Bin jetzt dabei...

2020-09-20 12:19 UTC, Gandalf1783 commented on modules/yt.js
>          .pipe(fs.createWriteStream(`videos/${videoInfo.id}.mp3`))
Ich lasse dies erstmal außen vor, weil ich mir nicht sicher bin, ob das immer noch so gut funktionieren würde. Ich wäre dafür, die ID‘s weiterhin zu nutzen, einfach weil sie Einmalig sind und genau für eine solche Verwendung wie hier vorgesehen sind.

2020-09-20 12:30 UTC, Gandalf1783 commented
Updated the Code. Please Review and commit if ready.

2020-10-21 12:35 UTC, Dad-Ju approved these changes

2020-10-21 12:37 UTC, merged