Update music-stop.js
Dad-Ju/hbz-discord-bot pull request #3
Opened 2021-02-03 20:06 UTC by Gandalf1783

Fixed an issue where the dispatcher returned NULL.

2021-02-03 23:28 UTC, VottusCode commented
NULL

2021-02-04 10:36 UTC, Dad-Ju requested changes
little Change ^^

2021-02-04 10:36 UTC, Dad-Ju commented on events/music-stop.js
> +        if(connection.dispatcher !== null) {
Ich bevorzuge gerne `typof x !== "undefined"`
das bitte umbauen dann kanns gemerged werden

2021-02-04 10:36 UTC, Dad-Ju commented on events/music-stop.js
> +        if(connection.dispatcher !== null) {
das kann außerdem nen oneliner sein einfach die geschweifeten klammern weg

2021-02-04 10:37 UTC, Dad-Ju commented on events/music-stop.js
> +        if(connection.dispatcher !== null) {
das const dispatcher = ist auch unnötig destry reicht. wir benutzen es hier nicht weiter

2021-02-04 13:41 UTC, closed without merging

2021-02-04 13:41 UTC, Gandalf1783 commented
Closed because bug does not occur in the current version of the code.